---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
  - name: ubuntu-12.04

suites:
  - name: slack
    run_list: recipe[chatops_notify_tests::slack_notify]
    attributes:
      webhook: <%= ENV['SLACK_WEBHOOK'] %>
      channel: <%= ENV['SLACK_CHANNEL'] %>
  - name: hipchat
    run_list: recipe[chatops_notify_tests::hipchat_notify]
    attributes:
      webhook: <%= ENV['HIPCHAT_WEBHOOK'] %>
