---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.7
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: slack
    run_list: recipe[chatops_notify_tests::slack_notify]
    attributes:
      webhook: <%= ENV['SLACK_WEBHOOK'] %>
      channel: <%= ENV['SLACK_CHANNEL'] %>
  - name: hipchat
    run_list: recipe[chatops_notify_tests::hipchat_notify]
    attributes:
      webhook: <%= ENV['HIPCHAT_WEBHOOK'] %>
